dotenv: .env
networks:
  default: development
  rinkeby:
    verify: True
  mainnet-fork-dev:
    verify: False
  development:
    verify: False
  ganache-local:
    verify: False
wallets:
  from_key_deployer: ${PRIVATE_KEY_REGISTRY}
  from_key_issuer : ${PRIVATE_KEY_ISSUER}